spring:
  application:
    name: aivle-central-4-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_ID}       # 데이터베이스 아이디
    password: ${DB_PW} # 데이터베이스 비밀번호
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  config:
    import: classpath:personal.yaml